CREATE PROCEDURE [dbo].[sp_SaveRefreshToken]
    @USER_ID INT,
    @REFRESH_TOKEN NVARCHAR(512),
    @EXPIRES_ON DATETIME2(7)
AS
BEGIN
    SET NOCOUNT ON;

    IF (@USER_ID IS NULL OR @USER_ID < 1)
    BEGIN
        RAISERROR(N'User is required.', 16, 1);
        RETURN;
    END

    IF (@REFRESH_TOKEN IS NULL OR LEN(LTRIM(RTRIM(@REFRESH_TOKEN))) = 0)
    BEGIN
        RAISERROR(N'Refresh token is required.', 16, 1);
        RETURN;
    END

    DELETE FROM dbo.USER_REFRESH_TOKENS
    WHERE USER_ID = @USER_ID;

    INSERT INTO dbo.USER_REFRESH_TOKENS (USER_ID, REFRESH_TOKEN, EXPIRES_ON)
    VALUES (@USER_ID, LTRIM(RTRIM(@REFRESH_TOKEN)), @EXPIRES_ON);
END
