CREATE TABLE [dbo].[CLIENTS] (
    [CLIENT_ID]     INT            IDENTITY (1, 1) NOT NULL,
    [CLIENT_CODE]   NVARCHAR (30)  NOT NULL,
    [CLIENT_NAME]   NVARCHAR (200) NOT NULL,
    [IS_ACTIVE]     BIT            NOT NULL CONSTRAINT [DF_CLIENTS_IS_ACTIVE] DEFAULT ((1)),
    [CREATED_DATE]  DATETIME2 (7)  NOT NULL CONSTRAINT [DF_CLIENTS_CREATED_DATE] DEFAULT (getdate()),
    [MODIFIED_DATE] DATETIME2 (7)  NULL,
    CONSTRAINT [PK_CLIENTS] PRIMARY KEY CLUSTERED ([CLIENT_ID] ASC),
    CONSTRAINT [UQ_CLIENTS_CODE] UNIQUE NONCLUSTERED ([CLIENT_CODE] ASC)
);
