CREATE TABLE [dbo].[COMPANY_MASTER] (
    [COMPANY_ID]              INT            IDENTITY (1, 1) NOT NULL,
    [CLIENT_ID]               INT            NOT NULL,
    [COMPANY_TYPE_ID]         INT            NULL,
    [COMPANY_CODE]            NVARCHAR (50)  NULL,
    [COMPANY_NAME]            NVARCHAR (200) NOT NULL,
    [GST_NUMBER]              NVARCHAR (50)  NULL,
    [ADDRESS]                 NVARCHAR (500) NULL,
    [CITY]                    NVARCHAR (100) NULL,
    [STATE]                   NVARCHAR (100) NULL,
    [PIN_CODE]                NVARCHAR (20)  NULL,
    [DATE_OF_ESTABLISHMENT]   DATE           NULL,
    [REG_NO]                  NVARCHAR (100) NULL,
    [TELEPHONE_NO]            NVARCHAR (30)  NULL,
    [MOBILE]                  NVARCHAR (20)  NULL,
    [WEBSITE]                 NVARCHAR (500) NULL,
    [PRODUCTS]                NVARCHAR (MAX) NULL,
    [IS_ACTIVE]               BIT            DEFAULT ((1)) NULL,
    [CREATED_DATE]            DATETIME2 (7)  DEFAULT (getdate()) NULL,
    [CREATED_BY]              INT            NULL,
    [MODIFIED_DATE]           DATETIME2 (7)  NULL,
    [MODIFIED_BY]             INT            NULL,
    PRIMARY KEY CLUSTERED ([COMPANY_ID] ASC),
    CONSTRAINT [FK_COMPANY_MASTER_CLIENTS] FOREIGN KEY ([CLIENT_ID]) REFERENCES [dbo].[CLIENTS] ([CLIENT_ID]),
    CONSTRAINT [FK_COMPANY_MASTER_COMPANY_TYPE] FOREIGN KEY ([COMPANY_TYPE_ID]) REFERENCES [dbo].[COMPANY_TYPE] ([COMPANY_TYPE_ID])
);
GO

CREATE UNIQUE NONCLUSTERED INDEX [UX_COMPANY_MASTER_CLIENT_GST]
    ON [dbo].[COMPANY_MASTER] ([CLIENT_ID] ASC, [GST_NUMBER] ASC)
    WHERE [GST_NUMBER] IS NOT NULL;
GO
CREATE UNIQUE NONCLUSTERED INDEX [UX_COMPANY_MASTER_CLIENT_CODE]
    ON [dbo].[COMPANY_MASTER] ([CLIENT_ID] ASC, [COMPANY_CODE] ASC)
    WHERE [COMPANY_CODE] IS NOT NULL;
