CREATE TABLE [dbo].[COMPANY_TYPE](
    [COMPANY_TYPE_ID] [int] IDENTITY(1,1) NOT NULL,
    [NAME] [nvarchar](150) NOT NULL,
    [CODE] [nvarchar](50) NOT NULL,
    [CREATED_DATE] [datetime2](7) NULL,
    [CREATED_BY] [int] NULL,
    [MODIFIED_BY] [int] NULL,
    [MODIFIED_DATE] [datetime2](7) NULL,
 CONSTRAINT [PK_COMPANY_TYPE] PRIMARY KEY CLUSTERED ([COMPANY_TYPE_ID] ASC),
 CONSTRAINT [UQ_COMPANY_TYPE_CODE] UNIQUE NONCLUSTERED ([CODE] ASC)
);
GO

ALTER TABLE [dbo].[COMPANY_TYPE] ADD DEFAULT (getdate()) FOR [CREATED_DATE];
GO
