CREATE TABLE [dbo].[FIRM_MEMBERS] (
    [FIRM_MEMBER_ID] INT           IDENTITY (1, 1) NOT NULL,
    [COMPANY_ID]     INT           NOT NULL,
    [MEMBER_ID]      INT           NOT NULL,
    [ROLE_IN_FIRM]   NVARCHAR (50) NOT NULL,
    [IS_ACTIVE]      BIT           DEFAULT ((1)) NULL,
    [LINKED_BY]      INT           NULL,
    [LINKED_AT]      DATETIME2 (7) DEFAULT (getdate()) NULL,
    [CREATED_DATE]   DATETIME2 (7) DEFAULT (getdate()) NULL,
    [CREATED_BY]     INT           NULL,
    [MODIFIED_DATE]  DATETIME2 (7) NULL,
    [MODIFIED_BY]    INT           NULL,
    PRIMARY KEY CLUSTERED ([FIRM_MEMBER_ID] ASC),
    CONSTRAINT [FK_FIRM_MEMBERS_COMPANY] FOREIGN KEY ([COMPANY_ID]) REFERENCES [dbo].[COMPANY_MASTER] ([COMPANY_ID]),
    CONSTRAINT [FK_FIRM_MEMBERS_MEMBER] FOREIGN KEY ([MEMBER_ID]) REFERENCES [dbo].[MEMBERS] ([MEMBER_ID])
);

