CREATE TABLE [dbo].[FIRM_DOCUMENTS] (
    [FIRM_DOC_ID]   INT            IDENTITY (1, 1) NOT NULL,
    [COMPANY_ID]    INT            NOT NULL,
    [DOCUMENT_TYPE] NVARCHAR (50)  NOT NULL,
    [BLOB_URL]      NVARCHAR (500) NOT NULL,
    [UPLOADED_BY]   INT            NULL,
    [UPLOADED_AT]   DATETIME2 (7)  DEFAULT (getdate()) NULL,
    [CREATED_DATE]  DATETIME2 (7)  DEFAULT (getdate()) NULL,
    [CREATED_BY]    INT            NULL,
    [MODIFIED_DATE] DATETIME2 (7)  NULL,
    [MODIFIED_BY]   INT            NULL,
    PRIMARY KEY CLUSTERED ([FIRM_DOC_ID] ASC),
    CONSTRAINT [FK_FIRM_DOCUMENTS_COMPANY] FOREIGN KEY ([COMPANY_ID]) REFERENCES [dbo].[COMPANY_MASTER] ([COMPANY_ID])
);

