CREATE TABLE [dbo].[INVOICES] (
    [INVOICE_ID]     INT             IDENTITY (1, 1) NOT NULL,
    [PAYMENT_ID]     INT             NOT NULL,
    [INVOICE_NUMBER] NVARCHAR (100)  NULL,
    [INVOICE_DATE]   DATETIME2 (7)   DEFAULT (getdate()) NULL,
    [TOTAL_AMOUNT]   DECIMAL (18, 2) NULL,
    [CREATED_DATE]   DATETIME2 (7)   DEFAULT (getdate()) NULL,
    [CREATED_BY]     INT             NULL,
    [MODIFIED_DATE]  DATETIME2 (7)   NULL,
    [MODIFIED_BY]    INT             NULL,
    PRIMARY KEY CLUSTERED ([INVOICE_ID] ASC),
    FOREIGN KEY ([PAYMENT_ID]) REFERENCES [dbo].[PAYMENTS] ([PAYMENT_ID]),
    UNIQUE NONCLUSTERED ([INVOICE_NUMBER] ASC)
);

