CREATE TABLE [dbo].[MEMBERS] (
    [MEMBER_ID]        INT            IDENTITY (1, 1) NOT NULL,
    [CLIENT_ID]        INT            NOT NULL,
    [APPLICATION_ID]   INT            NULL,
    [MEMBERSHIP_ID]    NVARCHAR (30)  NULL,
    [OWNER_NAME]       NVARCHAR (150) NULL,
    [EMAIL]            NVARCHAR (150) NULL,
    [MOBILE_NUMBER]    NVARCHAR (20)  NULL,
    [ADDRESS]          NVARCHAR (500) NULL,
    [CITY]             NVARCHAR (100) NULL,
    [DATE_OF_BIRTH]    DATE           NULL,
    [ANNIVERSARY_DATE] DATE           NULL,
    [IS_ACTIVE]        BIT            DEFAULT ((1)) NULL,
    [CREATED_DATE]     DATETIME2 (7)  DEFAULT (getdate()) NULL,
    [CREATED_BY]       INT            NULL,
    [MODIFIED_DATE]    DATETIME2 (7)  NULL,
    [MODIFIED_BY]      INT            NULL,
    [COMPANY_ID]       INT            NOT NULL,
    PRIMARY KEY CLUSTERED ([MEMBER_ID] ASC),
    CONSTRAINT [FK_MEMBERS_CLIENTS] FOREIGN KEY ([CLIENT_ID]) REFERENCES [dbo].[CLIENTS] ([CLIENT_ID]),
    FOREIGN KEY ([APPLICATION_ID]) REFERENCES [dbo].[MEMBER_APPLICATIONS] ([APPLICATION_ID]),
    CONSTRAINT [FK_MEMBERS_COMPANY] FOREIGN KEY ([COMPANY_ID]) REFERENCES [dbo].[COMPANY_MASTER] ([COMPANY_ID])
);

