CREATE TABLE [dbo].[MEMBER_APPLICATION_STATUS_HISTORY] (
    [HISTORY_ID]     INT           IDENTITY (1, 1) NOT NULL,
    [APPLICATION_ID] INT           NOT NULL,
    [OLD_STATUS]     NVARCHAR (50) NULL,
    [NEW_STATUS]     NVARCHAR (50) NULL,
    [CHANGED_BY]     INT           NULL,
    [CHANGED_DATE]   DATETIME2 (7) DEFAULT (getdate()) NULL,
    [CREATED_DATE]   DATETIME2 (7) DEFAULT (getdate()) NULL,
    [CREATED_BY]     INT           NULL,
    [MODIFIED_DATE]  DATETIME2 (7) NULL,
    [MODIFIED_BY]    INT           NULL,
    PRIMARY KEY CLUSTERED ([HISTORY_ID] ASC),
    FOREIGN KEY ([APPLICATION_ID]) REFERENCES [dbo].[MEMBER_APPLICATIONS] ([APPLICATION_ID]),
    FOREIGN KEY ([CHANGED_BY]) REFERENCES [dbo].[USERS] ([USER_ID])
);

