CREATE TABLE [dbo].[MEMBER_APPLICATIONS] (
    [APPLICATION_ID] INT            IDENTITY (1, 1) NOT NULL,
    [CLIENT_ID]      INT            NOT NULL,
    [COMPANY_NAME]   NVARCHAR (200) NOT NULL,
    [OWNER_NAME]     NVARCHAR (150) NULL,
    [EMAIL]          NVARCHAR (150) NULL,
    [MOBILE_NUMBER]  NVARCHAR (20)  NULL,
    [ADDRESS]        NVARCHAR (500) NULL,
    [CITY]           NVARCHAR (100) NULL,
    [STATUS]         NVARCHAR (50)  DEFAULT ('PENDING') NULL,
    [REMARKS]        NVARCHAR (500) NULL,
    [SUBMITTED_DATE] DATETIME2 (7)  DEFAULT (getdate()) NULL,
    [CREATED_DATE]   DATETIME2 (7)  DEFAULT (getdate()) NULL,
    [CREATED_BY]     INT            NULL,
    [MODIFIED_DATE]  DATETIME2 (7)  NULL,
    [MODIFIED_BY]    INT            NULL,
    PRIMARY KEY CLUSTERED ([APPLICATION_ID] ASC),
    CONSTRAINT [FK_MEMBER_APPLICATIONS_CLIENTS] FOREIGN KEY ([CLIENT_ID]) REFERENCES [dbo].[CLIENTS] ([CLIENT_ID])
);

