CREATE TABLE [dbo].[NOTIFICATION_LOGS] (
    [LOG_ID]          INT           IDENTITY (1, 1) NOT NULL,
    [NOTIFICATION_ID] INT           NULL,
    [MEMBER_ID]       INT           NULL,
    [SENT_DATE]       DATETIME2 (7) DEFAULT (getdate()) NULL,
    [STATUS]          NVARCHAR (50) NULL,
    [CREATED_DATE]    DATETIME2 (7) DEFAULT (getdate()) NULL,
    [CREATED_BY]      INT           NULL,
    [MODIFIED_DATE]   DATETIME2 (7) NULL,
    [MODIFIED_BY]     INT           NULL,
    PRIMARY KEY CLUSTERED ([LOG_ID] ASC),
    FOREIGN KEY ([MEMBER_ID]) REFERENCES [dbo].[MEMBERS] ([MEMBER_ID]),
    FOREIGN KEY ([NOTIFICATION_ID]) REFERENCES [dbo].[NOTIFICATIONS] ([NOTIFICATION_ID])
);

