CREATE TABLE [dbo].[NOTIFICATIONS] (
    [NOTIFICATION_ID] INT            IDENTITY (1, 1) NOT NULL,
    [MEMBER_ID]       INT            NULL,
    [TITLE]           NVARCHAR (200) NULL,
    [MESSAGE]         NVARCHAR (MAX) NULL,
    [TYPE]            NVARCHAR (50)  NULL,
    [CATEGORY]        NVARCHAR (50)  NULL,
    [LINK_TO]         NVARCHAR (500) NULL,
    [IS_READ]         BIT            DEFAULT ((0)) NOT NULL,
    [CREATED_DATE]    DATETIME2 (7)  DEFAULT (getdate()) NULL,
    [CREATED_BY]      INT            NULL,
    [MODIFIED_DATE]   DATETIME2 (7)  NULL,
    [MODIFIED_BY]     INT            NULL,
    PRIMARY KEY CLUSTERED ([NOTIFICATION_ID] ASC),
    CONSTRAINT [FK_NOTIFICATIONS_MEMBER] FOREIGN KEY ([MEMBER_ID]) REFERENCES [dbo].[MEMBERS] ([MEMBER_ID])
);

