CREATE TABLE [dbo].[OTP_VERIFICATIONS] (
    [OTP_ID]        INT           IDENTITY (1, 1) NOT NULL,
    [MOBILE_NUMBER] NVARCHAR (20) NULL,
    [OTP_CODE]      NVARCHAR (10) NULL,
    [IS_VERIFIED]   BIT           DEFAULT ((0)) NULL,
    [EXPIRY_TIME]   DATETIME2 (7) NULL,
    [CREATED_DATE]  DATETIME2 (7) DEFAULT (getdate()) NULL,
    [CREATED_BY]    INT           NULL,
    [MODIFIED_DATE] DATETIME2 (7) NULL,
    [MODIFIED_BY]   INT           NULL,
    PRIMARY KEY CLUSTERED ([OTP_ID] ASC)
);

