CREATE TABLE [dbo].[PAYMENTS] (
    [PAYMENT_ID]      INT             IDENTITY (1, 1) NOT NULL,
    [MEMBER_ID]       INT             NOT NULL,
    [SUBSCRIPTION_ID] INT             NULL,
    [AMOUNT]          DECIMAL (18, 2) NOT NULL,
    [PAYMENT_METHOD]  NVARCHAR (50)   NULL,
    [PAYMENT_STATUS]  NVARCHAR (50)   NULL,
    [TRANSACTION_ID]  NVARCHAR (200)  NULL,
    [PAID_DATE]       DATETIME2 (7)   NULL,
    [CREATED_DATE]    DATETIME2 (7)   DEFAULT (getdate()) NULL,
    [CREATED_BY]      INT             NULL,
    [MODIFIED_DATE]   DATETIME2 (7)   NULL,
    [MODIFIED_BY]     INT             NULL,
    PRIMARY KEY CLUSTERED ([PAYMENT_ID] ASC),
    FOREIGN KEY ([MEMBER_ID]) REFERENCES [dbo].[MEMBERS] ([MEMBER_ID]),
    FOREIGN KEY ([SUBSCRIPTION_ID]) REFERENCES [dbo].[SUBSCRIPTIONS] ([SUBSCRIPTION_ID])
);

