CREATE TABLE [dbo].[PERMISSIONS](
    [PERMISSION_ID] [int] IDENTITY(1,1) NOT NULL,
    [PERMISSION_CODE] [nvarchar](100) NOT NULL,
    [DESCRIPTION] [nvarchar](255) NULL,
    [CREATED_DATE] [datetime2](7) NULL,
    [CREATED_BY] [int] NULL,
    [MODIFIED_DATE] [datetime2](7) NULL,
    [MODIFIED_BY] [int] NULL,
 CONSTRAINT [PK_PERMISSIONS] PRIMARY KEY CLUSTERED ([PERMISSION_ID] ASC),
 CONSTRAINT [UQ_PERMISSIONS_CODE] UNIQUE NONCLUSTERED ([PERMISSION_CODE] ASC)
);
GO

ALTER TABLE [dbo].[PERMISSIONS] ADD DEFAULT (getdate()) FOR [CREATED_DATE];
GO
