CREATE TABLE [dbo].[ROLES] (
    [ROLE_ID]       INT            IDENTITY (1, 1) NOT NULL,
    [CLIENT_ID]     INT            NOT NULL,
    [ROLE_NAME]     NVARCHAR (50)  NOT NULL,
    [DESCRIPTION]   NVARCHAR (255) NULL,
    [PERMISSIONS]   NVARCHAR (MAX) NULL,
    [CREATED_DATE]  DATETIME2 (7)  DEFAULT (getdate()) NULL,
    [CREATED_BY]    INT            NULL,
    [MODIFIED_DATE] DATETIME2 (7)  NULL,
    [MODIFIED_BY]   INT            NULL,
    PRIMARY KEY CLUSTERED ([ROLE_ID] ASC),
    CONSTRAINT [FK_ROLES_CLIENTS] FOREIGN KEY ([CLIENT_ID]) REFERENCES [dbo].[CLIENTS] ([CLIENT_ID]),
    CONSTRAINT [UQ_ROLES_CLIENT_ROLE_NAME] UNIQUE NONCLUSTERED ([CLIENT_ID] ASC, [ROLE_NAME] ASC)
);
