CREATE TABLE [dbo].[ROLE_PERMISSION](
    [ROLE_ID] [int] NOT NULL,
    [PERMISSION_ID] [int] NOT NULL,
    [CREATED_DATE] [datetime2](7) NULL,
    [CREATED_BY] [int] NULL,
    [MODIFICATION_DATE] [datetime2](7) NULL,
    [MODIFIED_BY] [int] NULL,
 CONSTRAINT [PK_ROLE_PERMISSION] PRIMARY KEY CLUSTERED ([ROLE_ID] ASC, [PERMISSION_ID] ASC)
);
GO

ALTER TABLE [dbo].[ROLE_PERMISSION] ADD DEFAULT (getdate()) FOR [CREATED_DATE];
GO

ALTER TABLE [dbo].[ROLE_PERMISSION] WITH CHECK ADD CONSTRAINT [FK_ROLE_PERMISSION_ROLES]
    FOREIGN KEY ([ROLE_ID]) REFERENCES [dbo].[ROLES] ([ROLE_ID]) ON DELETE CASCADE;
GO

ALTER TABLE [dbo].[ROLE_PERMISSION] CHECK CONSTRAINT [FK_ROLE_PERMISSION_ROLES];
GO

ALTER TABLE [dbo].[ROLE_PERMISSION] WITH CHECK ADD CONSTRAINT [FK_ROLE_PERMISSION_PERMISSIONS]
    FOREIGN KEY ([PERMISSION_ID]) REFERENCES [dbo].[PERMISSIONS] ([PERMISSION_ID]);
GO

ALTER TABLE [dbo].[ROLE_PERMISSION] CHECK CONSTRAINT [FK_ROLE_PERMISSION_PERMISSIONS];
GO
