CREATE TABLE [dbo].[STAFF_PASSWORD_RESET](
    [RESET_ID] [int] IDENTITY(1,1) NOT NULL,
    [USER_ID] [int] NOT NULL,
    [CLIENT_ID] [int] NOT NULL,
    [TOKEN_HASH] [varbinary](32) NOT NULL,
    [EXPIRES_AT] [datetime2](7) NOT NULL,
    [CREATED_DATE] [datetime2](7) NULL,
    [USED_AT] [datetime2](7) NULL,
 CONSTRAINT [PK_STAFF_PASSWORD_RESET] PRIMARY KEY CLUSTERED ([RESET_ID] ASC)
);
GO

ALTER TABLE [dbo].[STAFF_PASSWORD_RESET] ADD DEFAULT (SYSUTCDATETIME()) FOR [CREATED_DATE];
GO

ALTER TABLE [dbo].[STAFF_PASSWORD_RESET] WITH CHECK ADD CONSTRAINT [FK_STAFF_PASSWORD_RESET_USERS]
    FOREIGN KEY ([USER_ID]) REFERENCES [dbo].[USERS] ([USER_ID]) ON DELETE CASCADE;
GO

ALTER TABLE [dbo].[STAFF_PASSWORD_RESET] CHECK CONSTRAINT [FK_STAFF_PASSWORD_RESET_USERS];
GO

ALTER TABLE [dbo].[STAFF_PASSWORD_RESET] WITH CHECK ADD CONSTRAINT [FK_STAFF_PASSWORD_RESET_CLIENTS]
    FOREIGN KEY ([CLIENT_ID]) REFERENCES [dbo].[CLIENTS] ([CLIENT_ID]);
GO

ALTER TABLE [dbo].[STAFF_PASSWORD_RESET] CHECK CONSTRAINT [FK_STAFF_PASSWORD_RESET_CLIENTS];
GO

CREATE NONCLUSTERED INDEX [IX_STAFF_PASSWORD_RESET_TOKEN_HASH]
    ON [dbo].[STAFF_PASSWORD_RESET] ([TOKEN_HASH] ASC)
    INCLUDE ([EXPIRES_AT], [USED_AT]);
