CREATE TABLE [dbo].[SUBSCRIPTIONS] (
    [SUBSCRIPTION_ID] INT           IDENTITY (1, 1) NOT NULL,
    [MEMBER_ID]       INT           NOT NULL,
    [PLAN_ID]         INT           NOT NULL,
    [START_DATE]      DATE          NOT NULL,
    [END_DATE]        DATE          NOT NULL,
    [STATUS]          NVARCHAR (50) DEFAULT ('ACTIVE') NULL,
    [CREATED_DATE]    DATETIME2 (7) DEFAULT (getdate()) NULL,
    [CREATED_BY]      INT           NULL,
    [MODIFIED_DATE]   DATETIME2 (7) NULL,
    [MODIFIED_BY]     INT           NULL,
    PRIMARY KEY CLUSTERED ([SUBSCRIPTION_ID] ASC),
    FOREIGN KEY ([MEMBER_ID]) REFERENCES [dbo].[MEMBERS] ([MEMBER_ID]),
    FOREIGN KEY ([PLAN_ID]) REFERENCES [dbo].[MEMBERSHIP_PLANS] ([PLAN_ID])
);

