CREATE TABLE [dbo].[TOKEN_DENYLIST] (
    [DENYLIST_ID]  INT            IDENTITY (1, 1) NOT NULL,
    [USER_ID]      INT            NOT NULL,
    [JTI]          NVARCHAR (100) NOT NULL,
    [REASON]       NVARCHAR (200) NULL,
    [CREATED_DATE] DATETIME2 (7)  DEFAULT (getdate()) NULL,
    PRIMARY KEY CLUSTERED ([DENYLIST_ID] ASC),
    CONSTRAINT [FK_TOKEN_DENYLIST_USER] FOREIGN KEY ([USER_ID]) REFERENCES [dbo].[USERS] ([USER_ID])
);

