CREATE TABLE [dbo].[USER_REFRESH_TOKENS](
    [REFRESH_TOKEN_ID] [int] IDENTITY(1,1) NOT NULL,
    [USER_ID] [int] NOT NULL,
    [REFRESH_TOKEN] [nvarchar](512) NOT NULL,
    [EXPIRES_ON] [datetime2](7) NOT NULL,
    [CREATED_DATE] [datetime2](7) NULL,
 CONSTRAINT [PK_USER_REFRESH_TOKENS] PRIMARY KEY CLUSTERED ([REFRESH_TOKEN_ID] ASC),
 CONSTRAINT [UQ_USER_REFRESH_TOKENS_TOKEN] UNIQUE NONCLUSTERED ([REFRESH_TOKEN] ASC)
);
GO

ALTER TABLE [dbo].[USER_REFRESH_TOKENS] ADD DEFAULT (SYSUTCDATETIME()) FOR [CREATED_DATE];
GO

ALTER TABLE [dbo].[USER_REFRESH_TOKENS] WITH CHECK ADD CONSTRAINT [FK_USER_REFRESH_TOKENS_USERS]
    FOREIGN KEY ([USER_ID]) REFERENCES [dbo].[USERS] ([USER_ID]) ON DELETE CASCADE;
GO

ALTER TABLE [dbo].[USER_REFRESH_TOKENS] CHECK CONSTRAINT [FK_USER_REFRESH_TOKENS_USERS];
GO

CREATE NONCLUSTERED INDEX [IX_USER_REFRESH_TOKENS_USER_ID]
    ON [dbo].[USER_REFRESH_TOKENS] ([USER_ID] ASC)
    INCLUDE ([EXPIRES_ON]);
