CREATE TABLE [dbo].[USERS](
	[USER_ID] [int] IDENTITY(1,1) NOT NULL,
	[USERNAME] [nvarchar](100) NOT NULL,
	[EMAIL] [nvarchar](150) NOT NULL,
	[PASSWORD_HASH] VARBINARY(500) NOT NULL,
	[IS_ACTIVE] [bit] NULL,
	[IS_FIRST_LOGIN] [bit] NULL,
	[MUST_CHANGE_PASSWORD] [bit] NULL,
	[CREATED_DATE] [datetime2](7) NULL,
	[CREATED_BY] [int] NULL,
	[MODIFIED_DATE] [datetime2](7) NULL,
	[MODIFIED_BY] [int] NULL,
	[CLIENT_ID] [int] NOT NULL,
	[PASSWORD_SALT] [varbinary](256) NULL,
	[FULL_NAME] [varchar](100) NULL,
	[MOBILE_NO] [varchar](15) NULL,	
 CONSTRAINT [PK_USERS] PRIMARY KEY CLUSTERED 
(
	[USER_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY],
 CONSTRAINT [UQ_USERS_CLIENT_EMAIL] UNIQUE NONCLUSTERED 
(
	[CLIENT_ID] ASC,
	[EMAIL] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY],
 CONSTRAINT [UQ_USERS_CLIENT_USERNAME] UNIQUE NONCLUSTERED 
(
	[CLIENT_ID] ASC,
	[USERNAME] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO

ALTER TABLE [dbo].[USERS]  WITH CHECK ADD  CONSTRAINT [FK_USERS_CLIENTS] FOREIGN KEY([CLIENT_ID])
REFERENCES [dbo].[CLIENTS] ([CLIENT_ID])
GO

ALTER TABLE [dbo].[USERS] CHECK CONSTRAINT [FK_USERS_CLIENTS]
GO

ALTER TABLE [dbo].[USERS] ADD  DEFAULT ((1)) FOR [IS_ACTIVE]
GO

ALTER TABLE [dbo].[USERS] ADD  DEFAULT ((1)) FOR [IS_FIRST_LOGIN]
GO

ALTER TABLE [dbo].[USERS] ADD  DEFAULT ((1)) FOR [MUST_CHANGE_PASSWORD]
GO

ALTER TABLE [dbo].[USERS] ADD  DEFAULT (getdate()) FOR [CREATED_DATE]
GO

