CREATE TABLE [dbo].[USER_ROLES] (
    [USER_ID] INT NOT NULL,
    [ROLE_ID] INT NOT NULL,
    CONSTRAINT [PK_USER_ROLES] PRIMARY KEY CLUSTERED ([USER_ID] ASC, [ROLE_ID] ASC)
);
GO

ALTER TABLE [dbo].[USER_ROLES] WITH CHECK ADD CONSTRAINT [FK_USER_ROLES_USERS]
    FOREIGN KEY ([USER_ID]) REFERENCES [dbo].[USERS] ([USER_ID]) ON DELETE CASCADE;
GO

ALTER TABLE [dbo].[USER_ROLES] CHECK CONSTRAINT [FK_USER_ROLES_USERS];
GO

ALTER TABLE [dbo].[USER_ROLES] WITH CHECK ADD CONSTRAINT [FK_USER_ROLES_ROLES]
    FOREIGN KEY ([ROLE_ID]) REFERENCES [dbo].[ROLES] ([ROLE_ID]);
GO

ALTER TABLE [dbo].[USER_ROLES] CHECK CONSTRAINT [FK_USER_ROLES_ROLES];
GO
