/*
    Temporary seed data for local / QA testing only.
    Safe to re-publish: runs only when no row exists with CLIENT_CODE = N'SEED_DEMO'.

    Login (JWT ClientId): use CLIENT_ID from dbo.CLIENTS where CLIENT_CODE = N'SEED_DEMO'.
    Test user seed.admin / Pass@123 — PBKDF2 SHA256 100k iter (matches CommandMethods.ValidatePassword).
*/

SET NOCOUNT ON;

IF EXISTS (SELECT 1 FROM dbo.CLIENTS WHERE CLIENT_CODE = N'SEED_DEMO')
BEGIN
    PRINT N'AMMS seed: SEED_DEMO client already exists — skipping test insert.';
    RETURN;
END;

DECLARE @cid           INT;
DECLARE @roleAdminId   INT;
DECLARE @roleManagerId INT;
DECLARE @userAdminId   INT;
DECLARE @companyId     INT;
DECLARE @appVerifiedId INT;
DECLARE @planAnnualId  INT;
DECLARE @member1Id     INT;
DECLARE @member2Id     INT;
DECLARE @subId         INT;
DECLARE @payId         INT;
DECLARE @notifId       INT;

/* Pass@123 — fixed salt so seed is reproducible */
DECLARE @pwdSalt VARBINARY(256) = 0xDEADBEEF0102030405060708090A0B0C;
DECLARE @pwdHash VARBINARY(500) = 0xFBCC16010585D1499637A4943F2FF9342414A6CFA62C9ED1FA0F2006B9FC630C;

INSERT INTO dbo.CLIENTS (CLIENT_CODE, CLIENT_NAME, IS_ACTIVE)
VALUES (N'SEED_DEMO', N'Seed Demo Tenant', 1);

SET @cid = CAST(SCOPE_IDENTITY() AS INT);

INSERT INTO dbo.ROLES (CLIENT_ID, ROLE_NAME, DESCRIPTION, PERMISSIONS)
VALUES (@cid, N'Admin', N'Seed administrator', N'["*"]');

SET @roleAdminId = CAST(SCOPE_IDENTITY() AS INT);

INSERT INTO dbo.ROLES (CLIENT_ID, ROLE_NAME, DESCRIPTION, PERMISSIONS)
VALUES (@cid, N'Manager', N'Seed manager', N'["members.read","members.write"]');

SET @roleManagerId = CAST(SCOPE_IDENTITY() AS INT);

INSERT INTO dbo.ROLE_PERMISSION (ROLE_ID, PERMISSION_ID, CREATED_DATE, CREATED_BY, MODIFICATION_DATE, MODIFIED_BY)
SELECT @roleAdminId, p.PERMISSION_ID, SYSUTCDATETIME(), NULL, SYSUTCDATETIME(), NULL
FROM dbo.PERMISSIONS p;

INSERT INTO dbo.ROLE_PERMISSION (ROLE_ID, PERMISSION_ID, CREATED_DATE, CREATED_BY, MODIFICATION_DATE, MODIFIED_BY)
SELECT @roleManagerId, p.PERMISSION_ID, SYSUTCDATETIME(), NULL, SYSUTCDATETIME(), NULL
FROM dbo.PERMISSIONS p
WHERE p.PERMISSION_CODE IN (N'members.read', N'members.write');

INSERT INTO dbo.USERS (
    CLIENT_ID, USERNAME, EMAIL, PASSWORD_HASH, PASSWORD_SALT,
    IS_ACTIVE, IS_FIRST_LOGIN, MUST_CHANGE_PASSWORD, FULL_NAME)
VALUES (
    @cid, N'seed.admin', N'seed.admin@example.com', @pwdHash, @pwdSalt,
    1, 0, 0, N'Seed Administrator');

SET @userAdminId = CAST(SCOPE_IDENTITY() AS INT);

INSERT INTO dbo.USER_ROLES (USER_ID, ROLE_ID)
VALUES (@userAdminId, @roleAdminId);

DECLARE @companyTypeLlc INT = (SELECT COMPANY_TYPE_ID FROM dbo.COMPANY_TYPE WHERE CODE = N'LLC');

INSERT INTO dbo.COMPANY_MASTER (
    CLIENT_ID, COMPANY_TYPE_ID, COMPANY_CODE, COMPANY_NAME, GST_NUMBER,
    ADDRESS, CITY, STATE, PIN_CODE,
    DATE_OF_ESTABLISHMENT, REG_NO, TELEPHONE_NO, MOBILE, WEBSITE, PRODUCTS,
    IS_ACTIVE)
VALUES (
    @cid, @companyTypeLlc, N'SEED-CMP-001', N'Seed Manufacturing Pvt Ltd', N'22AAAAA0000A1Z5',
    N'100 MIDC Industrial Area', N'Pune', N'Maharashtra', N'411001',
    CAST(N'2010-04-01' AS DATE), N'CIN-SEED-0001', N'020-40001000', N'9123456789',
    N'https://seed-mfg.example.com', N'Castings, Forgings, Fasteners',
    1);

SET @companyId = CAST(SCOPE_IDENTITY() AS INT);

INSERT INTO dbo.MEMBER_APPLICATIONS (
    CLIENT_ID, COMPANY_NAME, OWNER_NAME, EMAIL, MOBILE_NUMBER, ADDRESS, CITY, STATUS, SUBMITTED_DATE)
VALUES (
    @cid, N'Seed Manufacturing Pvt Ltd', N'Rajesh Kumar', N'rajesh@example.com', N'9876543210',
    N'Plot 12', N'Pune', N'VERIFIED', DATEADD(DAY, -30, SYSUTCDATETIME()));

SET @appVerifiedId = CAST(SCOPE_IDENTITY() AS INT);

INSERT INTO dbo.MEMBER_APPLICATIONS (
    CLIENT_ID, COMPANY_NAME, OWNER_NAME, EMAIL, MOBILE_NUMBER, ADDRESS, CITY, STATUS, SUBMITTED_DATE)
VALUES (
    @cid, N'Pending Traders LLP', N'Priya Singh', N'priya@example.com', N'9876543211',
    N'Shop 5', N'Mumbai', N'PENDING', SYSUTCDATETIME());

INSERT INTO dbo.MEMBERSHIP_PLANS (CLIENT_ID, PLAN_NAME, PRICE, VALIDITY_IN_MONTHS, IS_ACTIVE)
VALUES (@cid, N'Standard Annual', 4999.00, 12, 1);

SET @planAnnualId = CAST(SCOPE_IDENTITY() AS INT);

INSERT INTO dbo.MEMBERSHIP_PLANS (CLIENT_ID, PLAN_NAME, PRICE, VALIDITY_IN_MONTHS, IS_ACTIVE)
VALUES (@cid, N'Basic Monthly', 499.00, 1, 1);

INSERT INTO dbo.MEMBERS (
    CLIENT_ID, APPLICATION_ID, MEMBERSHIP_ID, OWNER_NAME, EMAIL, MOBILE_NUMBER,
    ADDRESS, CITY, COMPANY_ID, IS_ACTIVE)
VALUES (
    @cid, @appVerifiedId, N'AMMS-2026-SEED01', N'Rajesh Kumar', N'rajesh@example.com', N'9876543210',
    N'Plot 12', N'Pune', @companyId, 1);

SET @member1Id = CAST(SCOPE_IDENTITY() AS INT);

INSERT INTO dbo.MEMBERS (
    CLIENT_ID, APPLICATION_ID, OWNER_NAME, EMAIL, MOBILE_NUMBER,
    COMPANY_ID, IS_ACTIVE)
VALUES (
    @cid, NULL, N'Second Member', N'member2@example.com', N'9876500000',
    @companyId, 1);

SET @member2Id = CAST(SCOPE_IDENTITY() AS INT);

INSERT INTO dbo.MEMBER_APPLICATION_STATUS_HISTORY (
    APPLICATION_ID, OLD_STATUS, NEW_STATUS, CHANGED_BY, CHANGED_DATE, CREATED_BY)
VALUES (
    @appVerifiedId, N'PENDING', N'VERIFIED', @userAdminId, DATEADD(DAY, -28, SYSUTCDATETIME()), @userAdminId);

INSERT INTO dbo.SUBSCRIPTIONS (MEMBER_ID, PLAN_ID, START_DATE, END_DATE, STATUS, CREATED_BY)
VALUES (
    @member1Id, @planAnnualId,
    CAST(DATEADD(DAY, -25, SYSUTCDATETIME()) AS DATE),
    CAST(DATEADD(YEAR, 1, DATEADD(DAY, -25, SYSUTCDATETIME())) AS DATE),
    N'ACTIVE', @userAdminId);

SET @subId = CAST(SCOPE_IDENTITY() AS INT);

INSERT INTO dbo.PAYMENTS (
    MEMBER_ID, SUBSCRIPTION_ID, AMOUNT, PAYMENT_METHOD, PAYMENT_STATUS, TRANSACTION_ID, PAID_DATE, CREATED_BY)
VALUES (
    @member1Id, @subId, 4999.00, N'UPI', N'SUCCESS', N'TXN-SEED-001',
    DATEADD(DAY, -25, SYSUTCDATETIME()), @userAdminId);

SET @payId = CAST(SCOPE_IDENTITY() AS INT);

INSERT INTO dbo.INVOICES (PAYMENT_ID, INVOICE_NUMBER, INVOICE_DATE, TOTAL_AMOUNT, CREATED_BY)
VALUES (@payId, N'INV-SEED-001', DATEADD(DAY, -25, SYSUTCDATETIME()), 4999.00, @userAdminId);

INSERT INTO dbo.NOTIFICATIONS (
    MEMBER_ID, TITLE, MESSAGE, TYPE, CATEGORY, IS_READ, CREATED_BY)
VALUES (
    @member1Id, N'Welcome', N'Thanks for joining the association.', N'INFO', N'GENERAL', 0, @userAdminId);

SET @notifId = CAST(SCOPE_IDENTITY() AS INT);

INSERT INTO dbo.NOTIFICATION_LOGS (NOTIFICATION_ID, MEMBER_ID, STATUS, CREATED_BY)
VALUES (@notifId, @member1Id, N'SENT', @userAdminId);

INSERT INTO dbo.BROADCASTS (
    CLIENT_ID, TITLE, MESSAGE, CHANNEL, TARGET_FILTER, CREATED_BY,
    RECIPIENT_COUNT, DELIVERED_COUNT, FAILED_COUNT, IS_DELETED)
VALUES (
    @cid, N'Seed broadcast', N'This is sample broadcast content.', N'EMAIL',
    NULL, @userAdminId, 0, 0, 0, 0);

INSERT INTO dbo.AUDIT_LOGS (USER_ID, ACTION, ENTITY_NAME, ENTITY_ID, CREATED_BY)
VALUES (@userAdminId, N'SEED_INSERT', N'MEMBERS', @member1Id, @userAdminId);

INSERT INTO dbo.OTP_VERIFICATIONS (MOBILE_NUMBER, OTP_CODE, IS_VERIFIED, EXPIRY_TIME)
VALUES (N'9876543210', N'123456', 0, DATEADD(MINUTE, 10, SYSUTCDATETIME()));

INSERT INTO dbo.FIRM_DOCUMENTS (COMPANY_ID, DOCUMENT_TYPE, BLOB_URL, UPLOADED_BY, CREATED_BY)
VALUES (@companyId, N'GST_CERT', N'https://example.blob.core.windows.net/seed/gst-cert.pdf', @userAdminId, @userAdminId);

INSERT INTO dbo.FIRM_MEMBERS (
    COMPANY_ID, MEMBER_ID, ROLE_IN_FIRM, IS_ACTIVE, LINKED_BY, CREATED_BY)
VALUES (@companyId, @member1Id, N'OWNER', 1, @userAdminId, @userAdminId);

INSERT INTO dbo.LOGIN_HISTORY (USER_ID, LOGIN_TIME, IP_ADDRESS, IS_SUCCESS)
VALUES (@userAdminId, SYSUTCDATETIME(), N'127.0.0.1', 1);

INSERT INTO dbo.TOKEN_DENYLIST (USER_ID, JTI, REASON)
VALUES (@userAdminId, N'seed-sample-revoked-token', N'Seed row — safe to delete');

PRINT N'AMMS seed: inserted SEED_DEMO tenant (CLIENT_ID = ' + CAST(@cid AS NVARCHAR(11)) + N').';
